spring:
  application:
    name: myWebPage
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?serverTimezone=Asia/Seoul
    username: root
    password: asd123

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

